[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[[test.genesis]]
address = "BookWizfXJLgda24JdN1drgWzqw3ta3rU1vGotFjpNTH"
program = "./deps/serum-dex/dex/target/deploy/serum_dex.so"
